### ISSUE TITLE
Allow ipv4/ipv6 to be switched off during generation

### ISSUE THREAD

**Issue by mrclrchtr** [hetznercloud/packer-plugin-hcloud#160]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

It should be possible to disable ipv4 and/or ipv6 during generation. 

#### Use Case(s)

The image I want to build takes into account which network interfaces are available during generation and configures itself accordingly. It must therefore be possible to deactivate these so that only the active ones can be used later during operation.

**Comment by jooola** [comment]
Hi @mrclrchtr 

I am not sure to understand your request: What do you mean by generation ? Could you explain a bit more your problem?

If you have problem with leftover configuration on the image that you build, I recommend you to clean up the instance before making the snapshot. You can start by running [`cloud-init clean`](https://cloudinit.readthedocs.io/en/latest/reference/cli.html#clean) and clean even more things from there.

**Comment by mrclrchtr** [comment]
Hi @jooola,

thanks for the reply.
It's been a long time, so i'm not sure if i need it anymore...

But that's the point:
it's about this packer file: https://github.com/hcloud-talos/terraform-hcloud-talos/blob/main/_packer/talos-hcloud.pkr.hcl

I create a base image there, with the talos operating system as a snapshot, from which new instances can then be created.

It seems to be the case that I later have information about the IPs in the snapshot. But I'm not so sure anymore. I assumed this when I created the ticket.

**Comment by jooola** [comment]
I am not sure our packer plugin is the source of your problem. I don't know Talos, but I'd rather look into the configuration files used to configure the server during the first boot (`user-data`).

I am going to close this for now, feel free to comment again if you think the problem do come from our packer plugin.

**Comment by apricote** [comment]
I agree with @jooola on this. You are writing the talos disk image directly to the root disk, without booting it. Making a snapshot of this root disk should only include the unaltered talos disk image.

I am doing something very similar in https://github.com/apricote/flatcar-packer-hcloud/blob/main/flatcar.pkr.hcl with Flatcar images, and the images are uploaded/saved exactly as expected.

**Comment by mrclrchtr** [comment]
yes i think you are right. thank you!
