### ISSUE TITLE
feat: clear message on why snapshot creation failed 

### ISSUE THREAD

**Issue by kranurag7** [hetznercloud/packer-plugin-hcloud#165]
I build a lot snapshots with `packer-plugin-hcloud` for quick iterations and lately I'm experiencing the following error. 

`Build 'hcloud' errored after 13 minutes 2 seconds: Could not create snapshot: Creating image failed because of an unknown error. (unknown_error)` 

The only solution we have for now is to trigger the build again. This issue requests having a clear message on why the snapshot was not created. Was it timed out or something else happened? 

Happy to provider more inputs here if required.

**Comment by apricote** [comment]
`unknown_error` is an error code from the API. The only thing the API returned was `Creating image failed because of an unknown error. (unknown_error)`, so we can not add any additional details in the Packer provider.

If we had the Correlation ID of the request, we could check in our internal tracing system what exactly went wrong, but it looks like the Packer Plugin has no way to to enable those yet. I will open a PR for this.

I have also opened https://github.com/hetznercloud/hcloud-go/pull/411 to make sure we print the trace id for any server errors.

**Comment by apricote** [comment]
Both improvements were released in 1.4.0, so if this ever happens again, please open a new ticket with the improved error message :)

**Comment by kranurag7** [comment]
We are still facing this issue and this happened to me 5-6 times during the weekend. In most cases it's going well but sometimes it's existing with `unknown_error` too. 
```bash
==> hcloud: This can take some time
==> hcloud: Could not create snapshot: Creating image failed because of an unknown error. (unknown_error)
==> hcloud: Provisioning step had errors: Running the cleanup provisioner, if present...
==> hcloud: Destroying server...
==> hcloud: Deleting temporary SSH key...
Build 'hcloud' errored after 11 minutes 15 seconds: Could not create snapshot: Creating image failed because of an unknown error. (unknown_error)

==> Wait completed after 11 minutes 15 seconds

==> Some builds didn't complete successfully and had errors:
--> hcloud: Could not create snapshot: Creating image failed because of an unknown error. (unknown_error)

==> Builds finished but no artifacts were created.
```

- packer and plugin versions are: 
```bash
$ packer version
Packer v1.9.5

Your version of Packer is out of date! The latest version
is 1.10.3. You can update by downloading from www.packer.io/downloads
$ packer plugins installed
/home/k7/.config/packer/plugins/github.com/hetznercloud/hcloud/packer-plugin-hcloud_v1.4.0_x5.0_linux_amd64
```

**Comment by jooola** [comment]
Weird that the correlation IDs are not in the error messages, I just tested myself, and the correlation IDs are present in the API response headers for this endpoint.

Could you please double-check the version of the hcloud packer plugin that you are using?

To fix your issue, I suggest that you open a [support ticket](https://console.hetzner.cloud/support) so we can share more data, and debug this further.
