### ISSUE TITLE
Packer Crash when `image` cannot be found

### ISSUE THREAD

**Issue by mhutter** [hetznercloud/packer-plugin-hcloud#222]
#### Overview of the Issue

When the base image for sources cannot be found, Packer crashes with SIGSEGV instead of a usable error message.

#### Reproduction Steps

Given this template, Packer will crash on build:
```hcl
source "hcloud" "aarch64" {
  image = "fedora-38"
}
```

Note that the `fedora-38` image does not exist anymore.

### Plugin and Packer version

Packer v1.11.2

v1.5.4 of this plugin

### Simplified Packer Buildfile

https://github.com/mhutter/hcloud-packer-coreos/blob/60deb2515edd6f71679c2b9ab295beba1aede9b7/template.pkr.hcl

### Operating system and Environment details

Linux, x64

### Log Fragments and crash.log files

See https://github.com/mhutter/hcloud-packer-coreos/actions/runs/10372210073/job/28714404526

**Comment by jooola** [comment]
Thanks for the bug report, I can confirm the bug.

It will be solved with https://github.com/hetznercloud/packer-plugin-hcloud/pull/223
