### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by apricote** [hetznercloud/packer-plugin-hcloud#87]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Could you publish a new release of the packer builder? Latest release v1.0.5 is over a year old, and since then we have [merged many improvements](https://github.com/hashicorp/packer-plugin-hcloud/compare/v1.0.5...main) and also have a breaking API change (#83) that needs to be released. 

#### Use Case(s)

- Anyone using Packer on 32bit platforms will break with the api change
- We have customers that would like to use the merged improvements

#### Potential configuration

```
```

#### Potential References

Previously requested in #83.

**Comment by lbajolet-hashicorp** [comment]
Hi @apricote,

Sorry for not taking care of this until now.

We will release a new version of the plugin today, so users will be able to use the plugin again once it is released.

Apologies again for not taking care of this sooner.

**Comment by lbajolet-hashicorp** [comment]
Update: version 1.1.0 of the plugin is now available, using the v2 SDK, this should support 52-bit identifiers now.

Please confirm if the problem is fixed, and if so we can close this issue.

**Comment by apricote** [comment]
Thank you very much @lbajolet-hashicorp!
